### ISSUE TITLE
Bug: After added a new checklist opening an issue in Chrome is going failed

### ISSUE THREAD

**Issue by ghost** [umbrella-web/AdvancedChecklists-Jira#30]
We've seen the issue happened twice. After added a new checklists the hole issue is being hanging and Chrome failed.
But, in Safari it works good.

Examples:

https://sheknows.jira.com/browse/STYL-305
https://sheknows.jira.com/browse/PUBOPS-123

**Comment by umbrella-yuri-makarenko** [comment]
This is reproduced if added URL with hash, for example:
http://some-url.com/chanel-airport-show-spring-2016/#slide-4

**Comment by umbrella-yuri-makarenko** [comment]
Solved.
