### ISSUE TITLE
[To Release] Drag & Drop sorting by using y axis

### ISSUE THREAD

**Issue by umbrella-mikhail-menshinskiy** [umbrella-web/AdvancedChecklists-Jira#4]
https://github.com/umbrella-web/AdvancedChecklists-Jira/pull/22

**Comment by umbrella-yuri-makarenko** [comment]
@umbrella-mikhail-menshinskiy Can you explain what you want in this ticket?

**Comment by umbrella-mikhail-menshinskiy** [comment]
Lock the x axis dragging. Look in the trello, I can drag vertically only
